# Form implementation generated from reading ui file '.\ui\registration.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(484, 190)
        font = QtGui.QFont()
        font.setPointSize(10)
        Form.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(parent=Form)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.frame = QtWidgets.QFrame(parent=Form)
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.gridLayout = QtWidgets.QGridLayout(self.frame)
        self.gridLayout.setObjectName("gridLayout")
        self.label_3 = QtWidgets.QLabel(parent=self.frame)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 4, 0, 1, 1)
        self.le_login = QtWidgets.QLineEdit(parent=self.frame)
        self.le_login.setObjectName("le_login")
        self.gridLayout.addWidget(self.le_login, 3, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.frame)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.le_email = QtWidgets.QLineEdit(parent=self.frame)
        self.le_email.setObjectName("le_email")
        self.gridLayout.addWidget(self.le_email, 1, 1, 1, 1)
        self.le_password = QtWidgets.QLineEdit(parent=self.frame)
        self.le_password.setObjectName("le_password")
        self.gridLayout.addWidget(self.le_password, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.frame)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 3, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.frame)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.le_repeated_password = QtWidgets.QLineEdit(parent=self.frame)
        self.le_repeated_password.setObjectName("le_repeated_password")
        self.gridLayout.addWidget(self.le_repeated_password, 5, 1, 1, 1)
        self.verticalLayout.addWidget(self.frame)
        self.pb_confirm = QtWidgets.QPushButton(parent=Form)
        self.pb_confirm.setObjectName("pb_confirm")
        self.verticalLayout.addWidget(self.pb_confirm)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)
        Form.setTabOrder(self.le_email, self.le_login)
        Form.setTabOrder(self.le_login, self.le_password)
        Form.setTabOrder(self.le_password, self.le_repeated_password)
        Form.setTabOrder(self.le_repeated_password, self.pb_confirm)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Введите данные для регистрации:"))
        self.label_3.setText(_translate("Form", "Пароль"))
        self.label_4.setText(_translate("Form", "Повторите пароль"))
        self.label_5.setText(_translate("Form", "Логин"))
        self.label_2.setText(_translate("Form", "Почта"))
        self.pb_confirm.setText(_translate("Form", "Подтвердить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec())
